2022-02-14 10:40:32,653 [main] INFO com.classes.BaseTest - Loading all methods from -masterVO class
2022-02-14 10:40:32,656 [main] INFO com.utils._masterVO - Loading Properties file from: .//src//test//resources//sysconfig//Constant.properties
2022-02-14 10:40:32,660 [main] INFO com.utils._masterVO - Properties File Loaded successfully
2022-02-14 10:40:32,661 [main] INFO com.utils._masterVO - Loading Master Sheet from: src//test//resources//config//DataProvider.xlsx
2022-02-14 10:40:33,242 [main] INFO com.utils._masterVO - Master Sheet Loaded successfully
2022-02-14 10:40:33,244 [main] INFO com.utils._masterVO - Loading Client Library for Client Versioning from: .//src//test//resources//sysconfig//ClientLib.properties
2022-02-14 10:40:33,247 [main] INFO com.utils._masterVO - Client Library Loaded successfully
2022-02-14 10:40:33,505 [main] INFO com.utils._masterVO - loadGeoDomains Map returns ::ZO - AUTbKlI - AUToKa1C
2022-02-14 10:40:33,651 [main] INFO com.utils._masterVO - loadGeoDomains Map returns ::AR - AUT7dba - AUT63dCN
2022-02-14 10:40:33,771 [main] INFO com.utils._masterVO - loadGeoDomains Map returns ::SA - AUTO2Fm - AUTNelnh
2022-02-14 10:40:34,212 [main] INFO com.utils._masterVO - Loading test case file file from: .//src//test//resources//sysconfig//testCaseFile.properties
2022-02-14 10:40:34,226 [main] INFO com.utils._masterVO - Test cases file Loaded successfully
2022-02-14 10:40:34,228 [main] INFO com.utils._masterVO - Loading Web Cases Master file from: .//src//test//resources//config//testCaseFile.properties
2022-02-14 10:40:34,243 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-02-14 10:40:34,277 [main] INFO com.dbrepository.DBHandler - Entered Access Handler :: PostGreSQL
2022-02-14 10:40:34,282 [main] INFO com.commons.CacheController - New Cache DAO Loaded :: UPDATECACHE_VER = 1
2022-02-14 10:40:34,315 [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using log4j logging.
2022-02-14 10:40:34,393 [main] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2022-02-14 10:40:34,466 [main] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge145am1wfm54gh8830f|4d6025c5, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge145am1wfm54gh8830f|4d6025c5, idleConnectionTestPeriod -> 0, initialPoolSize -> 10, jdbcUrl -> jdbc:postgresql://172.30.38.120:5432/pretups_trunk, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 10, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2022-02-14 10:40:34,967 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getNetworkName()
2022-02-14 10:40:35,051 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: Network Name (Network GGN)
2022-02-14 10:40:35,052 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(AMOUNT_MULT_FACTOR)
2022-02-14 10:40:35,053 [main] INFO com.dbrepository.DBConnectionPool - Active Size:1 Cache Size:2
2022-02-14 10:40:35,134 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (100)
2022-02-14 10:40:35,137 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(MSISDN_PREFIX_LENGTH)
2022-02-14 10:40:35,138 [main] INFO com.dbrepository.DBConnectionPool - Active Size:2 Cache Size:1
2022-02-14 10:40:35,219 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (2)
2022-02-14 10:40:35,221 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(MAX_MSISDN_LENGTH)
2022-02-14 10:40:35,222 [main] INFO com.dbrepository.DBConnectionPool - Active Size:3 Cache Size:0
2022-02-14 10:40:35,439 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (15)
2022-02-14 10:40:35,440 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(USER_PRODUCT_MULTIPLE_WALLET)
2022-02-14 10:40:35,442 [main] INFO com.dbrepository.DBConnectionPool - Active Size:4 Cache Size:2
2022-02-14 10:40:35,525 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (false)
2022-02-14 10:40:35,526 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(EXTERNAL_DATE_FORMAT)
2022-02-14 10:40:35,528 [main] INFO com.dbrepository.DBConnectionPool - Active Size:5 Cache Size:1
2022-02-14 10:40:35,611 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (yyyy/MM/dd)
2022-02-14 10:40:35,613 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DATE_FORMAT_CAL_JAVA)
2022-02-14 10:40:35,615 [main] INFO com.dbrepository.DBConnectionPool - Active Size:6 Cache Size:0
2022-02-14 10:40:35,839 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (yyyy/MM/dd)
2022-02-14 10:40:35,841 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(OTH_COM_CHNL)
2022-02-14 10:40:35,843 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:9
2022-02-14 10:40:35,925 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (false)
2022-02-14 10:40:35,967 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DW_ALLOWED_GATEWAYS)
2022-02-14 10:40:35,968 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:9
2022-02-14 10:40:36,132 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching System Preference: 
2022-02-14 10:40:36,132 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getSystemPreference(PostGreSQLRepository.java:238)
	at com.utils._masterVO.loadPreferences(_masterVO.java:351)
	at com.utils._masterVO.loadVO(_masterVO.java:76)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:36,133 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (null)
2022-02-14 10:40:36,135 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DEFAULT_LANGUAGE)
2022-02-14 10:40:36,136 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:9
2022-02-14 10:40:36,216 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (en)
2022-02-14 10:40:36,218 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DEFAULT_COUNTRY)
2022-02-14 10:40:36,219 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:40:36,300 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (US)
2022-02-14 10:40:36,302 [main] INFO com.utils._masterVO - Display Locale set to: en_US
2022-02-14 10:40:57,370 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-02-14 10:40:57,401 [main] INFO com.utils._masterVO - Loading Messages Resource properties File from: .//src//test//resources//sysconfig//English.properties
2022-02-14 10:40:57,442 [main] INFO com.utils._masterVO - Messages Resource Properties file Loaded successfully
2022-02-14 10:40:57,443 [main] INFO com.utils._masterVO - Loading Messages Resource properties File from: .//src//test//resources//sysconfig//C2S_English.properties
2022-02-14 10:40:57,453 [main] INFO com.utils._masterVO - Messages Resource Properties file Loaded successfully
2022-02-14 10:40:57,454 [main] INFO com.dbrepository.PostGreSQLRepository - Entered getGatewayDetails('EXTGW','USSD','SMSC')
2022-02-14 10:40:57,455 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:40:57,458 [main] INFO com.dbrepository.PostGreSQLRepository - getGatewayDetails() :: select query: SELECT rmg.gateway_code, mg.gateway_type, rmg.login_id, rmg.PASSWORD, rmg.content_type, rmg.service_port, mg.req_password_plain FROM message_gateway mg, req_message_gateway rmg WHERE mg.gateway_code = rmg.gateway_code AND rmg.gateway_code IN ('EXTGW','USSD','SMSC')
2022-02-14 10:40:57,550 [main] INFO com.dbrepository.PostGreSQLRepository - Database Returns: [[Ljava.lang.Object;@5505ae1a[{{EXTGW,EXTGW,pretups,0971500a350af5c3d1c0b12221a0558c,XML,190,Y},{USSD,USSD,pretups,0971500a350af5c3d1c0b12221a0558c,XML,190,Y},{SMSC,SMSC,pretups,0971500a350af5c3d1c0b12221a0558c,PLAIN,190,Y}}]
2022-02-14 10:40:57,551 [main] INFO com.dbrepository.PostGreSQLRepository - Exiting getGatewayDetails()
2022-02-14 10:40:57,554 [main] INFO com.utils._APIUtil - Entered getAPIServices(EXTGW)
2022-02-14 10:40:57,564 [main] INFO com.utils._APIUtil - Exiting getAPIServices([])
2022-02-14 10:40:57,565 [main] INFO com.utils._masterVO - Loading Gateway Cases Master file from: .//src//test//resources//config//GatewayMaster.xlsx
2022-02-14 10:40:57,697 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,701 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,704 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,721 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,751 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,775 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,775 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,784 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,785 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,785 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,786 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,787 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,788 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,788 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,789 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,816 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,817 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,819 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,819 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,819 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,820 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,820 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,821 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,821 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,821 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,822 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,822 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,822 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,823 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,823 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,823 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,824 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,824 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,825 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,827 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,827 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,828 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,828 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,828 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,829 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,829 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,831 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,831 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:57,831 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:116)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:449)
	at com.utils._masterVO.loadVO(_masterVO.java:82)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:40:58,191 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-02-14 10:40:58,194 [main] INFO com.utils._APIUtil - Entered getAPIServices(USSD)
2022-02-14 10:40:58,195 [main] INFO com.utils._APIUtil - Exiting getAPIServices([])
2022-02-14 10:40:58,197 [main] INFO com.utils._masterVO - Loading Gateway Cases Master file from: .//src//test//resources//config//GatewayMaster.xlsx
2022-02-14 10:40:58,384 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-02-14 10:40:58,386 [main] INFO com.utils._masterVO - Loading Gateway Cases Master file from: .//src//test//resources//config//GatewayMaster.xlsx
2022-02-14 10:40:58,515 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-02-14 10:41:19,566 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-02-14 10:41:19,600 [main] INFO com.classes.BaseTest - Completed loading all methods from -masterVO class
2022-02-14 10:42:48,963 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_01_Test_getUserInfoApi_positive -------------------
2022-02-14 10:42:48,964 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_01_Test_getUserInfoApi_positive()
2022-02-14 10:42:49,006 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:42:49,006 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:42:50,746 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:42:52,084 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQ4Njc1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MTMxLjQwOC40NDgyIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIwMjMxMzQyMjE2Mjg0IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTI5MSwianRpIjoiMmZkMzNjZjQtOWYyMS00ZDYzLWE1M2ItOGY5ZWVlM2M2YmM0In0.YgFjwxXYujUs3uPaz6VR1ep9aAFL-dC8LI5PkBVBGZE","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQ4Njc1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MTMxLjQwOC40NDgyIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIwMjMxMzQyMjE2Mjg0IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTI5MSwianRpIjoiZTY0NjY5YWYtMjQ3YS00MDJmLThmMWItZDdlNDg0OTIzZDljIn0.2_8AYGP9iGg3C90Gz4uHWwkvFmzI2cBAZCYx9qYYSKE","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:42:52,146 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:42:52,700 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:42:52,703 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:42:52,704 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:42:52,871 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:42:52,872 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_01_Test_getUserInfoApi_positive(GetUserInfoApiTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:42:52,875 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (720231342216284)
2022-02-14 10:42:52,883 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:42:52,885 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:42:52,886 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:42:52,888 [main] INFO restassuredapi.api.BaseAPI - userId : 720231342216284

2022-02-14 10:42:54,691 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user 720231342216284 not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:42:54,705 [main] INFO com.classes.BaseTest - java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <400>.

2022-02-14 10:43:15,758 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-02-14 10:43:16,618 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_01_Test_getUserInfoApi_positive -------------------
2022-02-14 10:43:16,618 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_01_Test_getUserInfoApi_positive()
2022-02-14 10:43:16,620 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:43:16,620 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:43:16,624 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:43:17,012 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzE5OTk1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MTU2LjI2OS44NDEzIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI0Njk5MDg1NzUwMTU5IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTMxNiwianRpIjoiNWQ5ZGU1OTQtYzA2NC00YzI0LWJjYjgtZTQwMDliOWFmYWVjIn0.C_BRpLjKzUta4iBwXYrG2TVviEisbekRTtgpOR0whAA","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzE5OTk1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MTU2LjI2OS44NDEzIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI0Njk5MDg1NzUwMTU5IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTMxNiwianRpIjoiMTUyMjU2MmYtNDUxYi00NmExLTliZDYtMGMyZDFkMmZmYjJmIn0.KhENYztBfACNUkEhiQNq1DJwVAPZTN5ygakjh4oku4c","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:43:17,018 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:43:17,631 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:43:17,633 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:43:17,635 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:43:17,804 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:43:17,805 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_01_Test_getUserInfoApi_positive(GetUserInfoApiTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:43:17,808 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (724699085750159)
2022-02-14 10:43:17,810 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:43:17,811 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:43:17,813 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:43:17,815 [main] INFO restassuredapi.api.BaseAPI - userId : 724699085750159

2022-02-14 10:43:18,057 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user 724699085750159 not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:43:18,064 [main] INFO com.classes.BaseTest - java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <400>.

2022-02-14 10:43:39,117 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-02-14 10:43:39,743 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_01_Test_getUserInfoApi_positive -------------------
2022-02-14 10:43:39,743 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_01_Test_getUserInfoApi_positive()
2022-02-14 10:43:39,744 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:43:39,744 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:43:39,746 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:43:39,997 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzA4ODM3IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MjE5LjM5My44NTEiLCJyZXFHYXRld2F5VHlwZSI6IlJFU1QiLCJpc3MiOiJwcmV0dXBzLm9hdXRoIiwic2VydmljZVBvcnQiOiIxOTAiLCJtc2lzZG4iOiI3Mjg5MTY4OTk3NDI1MDAiLCJleHAiOjMwMDAwMCwicmVxR2F0ZXdheUNvZGUiOiJSRVNUIiwiaWF0IjoxNjQ0ODM1MzM5LCJqdGkiOiI5NmU4NTM4MS03MTg3LTQwMTktYTUyZC02Y2ZmZGQ3NWQwZWIifQ.rK0Yi1GxRUBA1J45hxc9nM_mX2dBuWDUmH8Swa-35ig","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzA4ODM3IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MjE5LjM5My44NTEiLCJyZXFHYXRld2F5VHlwZSI6IlJFU1QiLCJpc3MiOiJwcmV0dXBzLm9hdXRoIiwic2VydmljZVBvcnQiOiIxOTAiLCJtc2lzZG4iOiI3Mjg5MTY4OTk3NDI1MDAiLCJleHAiOjYwMDAwMCwicmVxR2F0ZXdheUNvZGUiOiJSRVNUIiwiaWF0IjoxNjQ0ODM1MzM5LCJqdGkiOiI3ODJmZDkxMy0zYjFhLTRkYzgtOWNlNy01NjNlNGE4ZjQ5YTMifQ.sEPgCs2NFaM_WsL55pRxFoDvn8XdqOPXuHNYSNe-PnQ","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:43:40,003 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:43:40,564 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:43:40,566 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:43:40,567 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:43:40,740 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:43:40,741 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_01_Test_getUserInfoApi_positive(GetUserInfoApiTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:43:40,744 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (728916899742500)
2022-02-14 10:43:40,747 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:43:40,748 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:43:40,750 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:43:40,752 [main] INFO restassuredapi.api.BaseAPI - userId : 728916899742500

2022-02-14 10:43:40,981 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user 728916899742500 not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:43:40,988 [main] INFO com.classes.BaseTest - java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <400>.

2022-02-14 10:44:02,041 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-02-14 10:44:02,692 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_01_Test_getUserInfoApi_positive -------------------
2022-02-14 10:44:02,692 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_01_Test_getUserInfoApi_positive()
2022-02-14 10:44:02,694 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:02,694 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:02,696 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:02,929 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzg3NTcwIiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MjQyLjMyOS42NzA5IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIzOTMyMDQ5MTk5NjI1IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTM2MiwianRpIjoiZWI0MmNjMWItNmFkNi00ZjQyLWE4NDctZGZkYmYwOTlhOTY2In0.AKA0X-2fQGfqlCS6zw62UUEgCRs2fx21Y4DGv1yJUHg","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzg3NTcwIiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MjQyLjMyOS42NzA5IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIzOTMyMDQ5MTk5NjI1IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTM2MiwianRpIjoiYmUwNWFlZGUtMDEwMC00ZjYzLWJlYjYtMjNhMThkYjBiYzM4In0.xglWbd1EYOKzBuAZlCefV6p71u1cjqi5TUS_1pVFDWk","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:02,937 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:03,507 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:03,508 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:44:03,510 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:44:03,859 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:44:03,860 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_01_Test_getUserInfoApi_positive(GetUserInfoApiTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:44:03,863 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (723932049199625)
2022-02-14 10:44:03,864 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:03,867 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:03,869 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:44:03,871 [main] INFO restassuredapi.api.BaseAPI - userId : 723932049199625

2022-02-14 10:44:04,150 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user 723932049199625 not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:04,158 [main] INFO com.classes.BaseTest - java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <400>.

2022-02-14 10:44:25,195 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-02-14 10:44:25,834 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_01_Test_getUserInfoApi_positive -------------------
2022-02-14 10:44:25,834 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_01_Test_getUserInfoApi_positive()
2022-02-14 10:44:25,835 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:25,836 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:25,839 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:26,091 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQxNzI2IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzA1LjQ3OS42MzE3IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI2MTQyODEzNTQ2ODg2IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTM4NSwianRpIjoiZTM0NjYyODctYjc4NC00NDQ1LThhMjktZWUxZjJmMGI4OGMyIn0.PBwPs3p6NTZcuLI8NX67mdFdovCxASrhIsKECvQK5yU","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQxNzI2IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzA1LjQ3OS42MzE3IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI2MTQyODEzNTQ2ODg2IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTM4NSwianRpIjoiNzI1NTI2MWEtM2M3Ny00YzVkLWFlMzgtYTMzZWQzYjU4ZGIxIn0.n_UacN_YC6AiuRSguC3DMJmnRxsA_BRoXTK77rgze7Y","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:26,095 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:26,644 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:26,646 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:44:26,647 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:44:26,809 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:44:26,810 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_01_Test_getUserInfoApi_positive(GetUserInfoApiTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:44:26,812 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (726142813546886)
2022-02-14 10:44:26,815 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:26,816 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:26,818 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:44:26,820 [main] INFO restassuredapi.api.BaseAPI - userId : 726142813546886

2022-02-14 10:44:27,056 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user 726142813546886 not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:27,059 [main] INFO com.classes.BaseTest - java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <400>.

2022-02-14 10:44:48,080 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-02-14 10:44:48,804 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_02_Test_InvalidNetworkCode -------------------
2022-02-14 10:44:48,804 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_02_Test_InvalidNetworkCode()
2022-02-14 10:44:48,806 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:48,806 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:48,810 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:49,044 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQ4Njc1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzI4LjQ1Ni42MTkiLCJyZXFHYXRld2F5VHlwZSI6IlJFU1QiLCJpc3MiOiJwcmV0dXBzLm9hdXRoIiwic2VydmljZVBvcnQiOiIxOTAiLCJtc2lzZG4iOiI3MjAyMzEzNDIyMTYyODQiLCJleHAiOjMwMDAwMCwicmVxR2F0ZXdheUNvZGUiOiJSRVNUIiwiaWF0IjoxNjQ0ODM1NDA4LCJqdGkiOiIwODdkNmQ5OC0yYTUyLTQ1MmEtYTc0My1lNjc3NWZhMDEyNzcifQ.n_ig0LDVzLTSNt1rtpBea1kV2fGIcGLbuf2enMNaHUE","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQ4Njc1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzI4LjQ1Ni42MTkiLCJyZXFHYXRld2F5VHlwZSI6IlJFU1QiLCJpc3MiOiJwcmV0dXBzLm9hdXRoIiwic2VydmljZVBvcnQiOiIxOTAiLCJtc2lzZG4iOiI3MjAyMzEzNDIyMTYyODQiLCJleHAiOjYwMDAwMCwicmVxR2F0ZXdheUNvZGUiOiJSRVNUIiwiaWF0IjoxNjQ0ODM1NDA4LCJqdGkiOiIwNzJjMGUwNy0yMGU5LTRlMGEtOWUxNS0xYWVjMTQ5NGFjMzYifQ.4MZmY9blFNZdXX9R7DpP2-8HR3FKnzQPA7l7Qp_eGN4","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:49,051 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:49,580 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:49,582 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:44:49,584 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:44:49,745 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:44:49,745 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_02_Test_InvalidNetworkCode(GetUserInfoApiTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:44:49,747 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (720231342216284)
2022-02-14 10:44:49,749 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:49,750 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:49,752 [main] INFO restassuredapi.api.BaseAPI - networkCode : WgR

2022-02-14 10:44:49,753 [main] INFO restassuredapi.api.BaseAPI - userId : 720231342216284

2022-02-14 10:44:49,966 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"1004011","message":"External network code WgR is invalid.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:49,977 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>External network code WgR is invalid.<br><b>Found: </b>External network code WgR is invalid.</pre>
2022-02-14 10:44:50,540 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_02_Test_InvalidNetworkCode -----------------
2022-02-14 10:44:50,623 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_02_Test_InvalidNetworkCode -------------------
2022-02-14 10:44:50,623 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_02_Test_InvalidNetworkCode()
2022-02-14 10:44:50,624 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:50,625 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:50,630 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:50,903 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzE5OTk1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzMwLjI2NS4yNDUiLCJyZXFHYXRld2F5VHlwZSI6IlJFU1QiLCJpc3MiOiJwcmV0dXBzLm9hdXRoIiwic2VydmljZVBvcnQiOiIxOTAiLCJtc2lzZG4iOiI3MjQ2OTkwODU3NTAxNTkiLCJleHAiOjMwMDAwMCwicmVxR2F0ZXdheUNvZGUiOiJSRVNUIiwiaWF0IjoxNjQ0ODM1NDEwLCJqdGkiOiIxNzczZWExNi1mYTk3LTQ5MDQtOGVkZC1mYzUxMmZmMTJhZjIifQ.lvb0CXuuQf78BOxHkfZF01tKb705ns8iYpyHUacLt_U","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzE5OTk1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzMwLjI2NS4yNDUiLCJyZXFHYXRld2F5VHlwZSI6IlJFU1QiLCJpc3MiOiJwcmV0dXBzLm9hdXRoIiwic2VydmljZVBvcnQiOiIxOTAiLCJtc2lzZG4iOiI3MjQ2OTkwODU3NTAxNTkiLCJleHAiOjYwMDAwMCwicmVxR2F0ZXdheUNvZGUiOiJSRVNUIiwiaWF0IjoxNjQ0ODM1NDEwLCJqdGkiOiI5MGY5YTM3Yi0xNWY4LTQ5MjAtODc3Ny0yNDM0Y2NkNTVhYWEifQ.YrwOQ3UuwVpxPDx1Ox1q7wuSendFCt-bMyZaSFnwPdQ","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:50,910 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:51,495 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:51,496 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:44:51,497 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:44:51,669 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:44:51,669 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_02_Test_InvalidNetworkCode(GetUserInfoApiTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:44:51,671 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (724699085750159)
2022-02-14 10:44:51,674 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:51,676 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:51,677 [main] INFO restassuredapi.api.BaseAPI - networkCode : jeM

2022-02-14 10:44:51,679 [main] INFO restassuredapi.api.BaseAPI - userId : 724699085750159

2022-02-14 10:44:51,888 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"1004011","message":"External network code jeM is invalid.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:51,895 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>External network code jeM is invalid.<br><b>Found: </b>External network code jeM is invalid.</pre>
2022-02-14 10:44:52,437 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_02_Test_InvalidNetworkCode -----------------
2022-02-14 10:44:52,506 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_02_Test_InvalidNetworkCode -------------------
2022-02-14 10:44:52,506 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_02_Test_InvalidNetworkCode()
2022-02-14 10:44:52,507 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:52,507 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:52,510 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:52,743 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzA4ODM3IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzMyLjE1NS4yMDEzIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI4OTE2ODk5NzQyNTAwIiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxMiwianRpIjoiNTA0MjFjMTEtZmY1OC00OTM5LWJhN2EtNjU0YjIyN2M4Nzk4In0.yxMCcA16FagrxceNseAZhammLQEwT5t5Page_IsbS1U","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzA4ODM3IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzMyLjE1NS4yMDEzIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI4OTE2ODk5NzQyNTAwIiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxMiwianRpIjoiMWJlMjUyNjMtNmNjMC00ODM0LTkwNDctOThkNWJlMzhlOWUyIn0.L8BlnzPHlQRPpgW3h2ictzkpsRlKBk65k2U-Gpg1ICQ","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:52,751 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:53,312 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:53,313 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:44:53,314 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:44:53,482 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:44:53,482 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_02_Test_InvalidNetworkCode(GetUserInfoApiTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:44:53,484 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (728916899742500)
2022-02-14 10:44:53,486 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:53,488 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:53,489 [main] INFO restassuredapi.api.BaseAPI - networkCode : AhL

2022-02-14 10:44:53,491 [main] INFO restassuredapi.api.BaseAPI - userId : 728916899742500

2022-02-14 10:44:53,730 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"1004011","message":"External network code AhL is invalid.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:53,739 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>External network code AhL is invalid.<br><b>Found: </b>External network code AhL is invalid.</pre>
2022-02-14 10:44:54,285 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_02_Test_InvalidNetworkCode -----------------
2022-02-14 10:44:54,354 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_02_Test_InvalidNetworkCode -------------------
2022-02-14 10:44:54,354 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_02_Test_InvalidNetworkCode()
2022-02-14 10:44:54,356 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:54,356 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:54,360 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:54,580 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzg3NTcwIiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM0LjAwMC43NTYxIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIzOTMyMDQ5MTk5NjI1IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxNCwianRpIjoiYmY4MjRlY2EtM2NlNi00NDk2LWE5YTAtMGFjNTRlOTk5Y2ViIn0.zG6pD55_n8Y9NfYiHCzyGsG-ETC7YLnigJlkMZzOfEI","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzg3NTcwIiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM0LjAwMC43NTYxIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIzOTMyMDQ5MTk5NjI1IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxNCwianRpIjoiMmIzZmUxMGEtZTc4Zi00ZjBjLTkxZTYtNTIzMTZmNzFiNDgwIn0.EL96dhxpoDZ9ctmaxFQJdMEGinFgFrlKGBdgHdzztQA","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:54,583 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:55,172 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:55,174 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:44:55,176 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:44:55,382 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:44:55,383 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_02_Test_InvalidNetworkCode(GetUserInfoApiTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:44:55,386 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (723932049199625)
2022-02-14 10:44:55,391 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:55,393 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:55,395 [main] INFO restassuredapi.api.BaseAPI - networkCode : lRP

2022-02-14 10:44:55,397 [main] INFO restassuredapi.api.BaseAPI - userId : 723932049199625

2022-02-14 10:44:55,620 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"1004011","message":"External network code lRP is invalid.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:55,630 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>External network code lRP is invalid.<br><b>Found: </b>External network code lRP is invalid.</pre>
2022-02-14 10:44:56,194 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_02_Test_InvalidNetworkCode -----------------
2022-02-14 10:44:56,256 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_02_Test_InvalidNetworkCode -------------------
2022-02-14 10:44:56,256 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_02_Test_InvalidNetworkCode()
2022-02-14 10:44:56,257 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:56,257 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:56,259 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:56,489 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQxNzI2IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM1LjkwMS41OTM0IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI2MTQyODEzNTQ2ODg2IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxNSwianRpIjoiMTgxOGNkODYtZDllNC00N2I5LTk4ZTUtZDI4MmQ5MjQ0ZmQ3In0.9jqHK7ZZAS4Eod96xF5dwF2dOHJG0O4q0TLGCJ_EvPM","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQxNzI2IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM1LjkwMS41OTM0IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI2MTQyODEzNTQ2ODg2IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxNSwianRpIjoiYTFhODUyYmEtYTZlZi00NTIzLTk4ZjQtNTg3NWMwNzNkMmU5In0.V0xizLOcpY8-re4PIdGOIhM5DnANrboQY0oEHVnV9Kk","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:56,497 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:57,063 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:57,066 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-02-14 10:44:57,067 [main] INFO com.dbrepository.PostGreSQLRepository - Entered:: getUserIdFromMsisdn()
2022-02-14 10:44:57,233 [main] INFO com.dbrepository.PostGreSQLRepository - Exception while fetching NAME: 
2022-02-14 10:44:57,234 [main] INFO com.dbrepository.PostGreSQLRepository - org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
	at org.postgresql.jdbc.PgResultSet.checkResultSet(PgResultSet.java:2772)
	at org.postgresql.jdbc.PgResultSet.getString(PgResultSet.java:1894)
	at com.mchange.v2.c3p0.impl.NewProxyResultSet.getString(NewProxyResultSet.java:4865)
	at com.dbrepository.PostGreSQLRepository.getUserIdFromMsisdn(PostGreSQLRepository.java:4439)
	at restassuredapi.test.GetUserInfoApiTest.A_02_Test_InvalidNetworkCode(GetUserInfoApiTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-02-14 10:44:57,235 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: user_Name (726142813546886)
2022-02-14 10:44:57,237 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:57,239 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:57,241 [main] INFO restassuredapi.api.BaseAPI - networkCode : QDH

2022-02-14 10:44:57,242 [main] INFO restassuredapi.api.BaseAPI - userId : 726142813546886

2022-02-14 10:44:57,478 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"1004011","message":"External network code QDH is invalid.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:57,485 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>External network code QDH is invalid.<br><b>Found: </b>External network code QDH is invalid.</pre>
2022-02-14 10:44:58,054 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_02_Test_InvalidNetworkCode -----------------
2022-02-14 10:44:58,160 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_03_Test_InvalidUserId -------------------
2022-02-14 10:44:58,160 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_03_Test_InvalidUserId()
2022-02-14 10:44:58,163 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:58,163 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:58,166 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:44:58,389 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQ4Njc1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM3LjgwOC43NTk4IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIwMjMxMzQyMjE2Mjg0IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxNywianRpIjoiZmE2ZDBiY2MtYmQ4OC00MDY1LWE0MmYtZDFmOTUzYjYwNDUxIn0.OH0z6-AKfI8rrgho7xhnd3uEiZ_aymIH68d0j18Cgm0","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQ4Njc1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM3LjgwOC43NTk4IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzIwMjMxMzQyMjE2Mjg0IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxNywianRpIjoiMGZjNDJiMTgtMjk0ZC00OTVmLWJiY2ItYzBjYjc4ZjI1ZGQ4In0.gYQBLvfTWHCz2t7lacExBkmIaRmWJFveODyAo-_TYIE","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:44:58,394 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:44:58,954 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:44:58,955 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:44:58,956 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:44:58,958 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:44:58,959 [main] INFO restassuredapi.api.BaseAPI - userId : eg79l4BA

2022-02-14 10:44:59,182 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user eg79l4BA not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:44:59,189 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>Details of user eg79l4BA not found.<br><b>Found: </b>Details of user eg79l4BA not found.</pre>
2022-02-14 10:44:59,726 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_03_Test_InvalidUserId -----------------
2022-02-14 10:44:59,794 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_03_Test_InvalidUserId -------------------
2022-02-14 10:44:59,795 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_03_Test_InvalidUserId()
2022-02-14 10:44:59,796 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:44:59,796 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:44:59,798 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:45:00,030 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzE5OTk1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM5LjQ0Ny42MzM2IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI0Njk5MDg1NzUwMTU5IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxOSwianRpIjoiMTVkMzA0YjQtY2MyNi00ZDA1LWFjZjEtZjc3NTZiNDIxNTliIn0.fPPHekhSK-CYOSflNSyvYzJshoz9qDyHWTpac7H-dek","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzE5OTk1IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzM5LjQ0Ny42MzM2IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI0Njk5MDg1NzUwMTU5IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQxOSwianRpIjoiZDFkNjVhY2UtZDgyOS00ZWZmLWExM2EtMTdmYmFhYjc2YjFjIn0.HQ99c_PTv2bQYjLMMZxq1uHT3VYdpExA5Drwrr3pPdY","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:45:00,035 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:45:00,598 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:45:00,600 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:45:00,601 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:45:00,603 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:45:00,605 [main] INFO restassuredapi.api.BaseAPI - userId : O3nE2nI9

2022-02-14 10:45:00,829 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user O3nE2nI9 not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:45:00,835 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>Details of user O3nE2nI9 not found.<br><b>Found: </b>Details of user O3nE2nI9 not found.</pre>
2022-02-14 10:45:01,393 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_03_Test_InvalidUserId -----------------
2022-02-14 10:45:01,450 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_03_Test_InvalidUserId -------------------
2022-02-14 10:45:01,451 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_03_Test_InvalidUserId()
2022-02-14 10:45:01,452 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:45:01,452 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:45:01,456 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:45:01,685 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzA4ODM3IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzQxLjEwMy41ODM1IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI4OTE2ODk5NzQyNTAwIiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQyMSwianRpIjoiMDY4NGM0OTctNTI4Ni00ZTkzLTk5ZDgtY2E3OWZiZjcwMjJkIn0.DrUIFHfPCufEuh2b_e_saHAvHNNeU9RKXRY0aK-MYv4","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzA4ODM3IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzQxLjEwMy41ODM1IiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI4OTE2ODk5NzQyNTAwIiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQyMSwianRpIjoiOGYzMWQ2ZTUtMmVmMy00OThlLWI2NTYtNGU4YWRmOWViOWY3In0.fobG4b7qL1HVcRdJnLCmILR2DfYTtEfCELLRXxWvQWQ","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:45:01,690 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:45:02,225 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:45:02,227 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:45:02,229 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:45:02,230 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:45:02,231 [main] INFO restassuredapi.api.BaseAPI - userId : H059amF4

2022-02-14 10:45:02,582 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user H059amF4 not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:45:02,588 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>Details of user H059amF4 not found.<br><b>Found: </b>Details of user H059amF4 not found.</pre>
2022-02-14 10:45:03,144 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_03_Test_InvalidUserId -----------------
2022-02-14 10:45:03,214 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_03_Test_InvalidUserId -------------------
2022-02-14 10:45:03,215 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_03_Test_InvalidUserId()
2022-02-14 10:45:03,216 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:45:03,216 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:45:03,221 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:45:03,442 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzg3NTcwIiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzQyLjg2NC4xOCIsInJlcUdhdGV3YXlUeXBlIjoiUkVTVCIsImlzcyI6InByZXR1cHMub2F1dGgiLCJzZXJ2aWNlUG9ydCI6IjE5MCIsIm1zaXNkbiI6IjcyMzkzMjA0OTE5OTYyNSIsImV4cCI6MzAwMDAwLCJyZXFHYXRld2F5Q29kZSI6IlJFU1QiLCJpYXQiOjE2NDQ4MzU0MjIsImp0aSI6IjI1YzRjZjhjLWRmZjYtNDJmZC04NGU5LTE3NDAwNTVlM2EzYiJ9.vPsLdaxoSpqIt2rV-5gXGBagtFknBriAG5te-6BlZCU","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzg3NTcwIiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzQyLjg2NC4xOCIsInJlcUdhdGV3YXlUeXBlIjoiUkVTVCIsImlzcyI6InByZXR1cHMub2F1dGgiLCJzZXJ2aWNlUG9ydCI6IjE5MCIsIm1zaXNkbiI6IjcyMzkzMjA0OTE5OTYyNSIsImV4cCI6NjAwMDAwLCJyZXFHYXRld2F5Q29kZSI6IlJFU1QiLCJpYXQiOjE2NDQ4MzU0MjIsImp0aSI6Ijk4ZmJlNTY0LTMzZmYtNGMwZS1hOTU4LWVhMGYyN2FiNmQ1MyJ9.CnOIF7eHxKzkFFeEz5UzuTvL48laBYMql3GzbvC8ZvA","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:45:03,461 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:45:04,032 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:45:04,033 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:45:04,035 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:45:04,036 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:45:04,037 [main] INFO restassuredapi.api.BaseAPI - userId : oEhB05jE

2022-02-14 10:45:04,259 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user oEhB05jE not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:45:04,264 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>Details of user oEhB05jE not found.<br><b>Found: </b>Details of user oEhB05jE not found.</pre>
2022-02-14 10:45:04,796 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_03_Test_InvalidUserId -----------------
2022-02-14 10:45:04,858 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For A_03_Test_InvalidUserId -------------------
2022-02-14 10:45:04,858 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered A_03_Test_InvalidUserId()
2022-02-14 10:45:04,860 [main] INFO restassuredapi.test.GetUserInfoApiTest - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-02-14 10:45:04,860 [main] INFO restassuredapi.test.GetUserInfoApiTest - Entered Test_OAuthenticationTest()
2022-02-14 10:45:04,864 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-02-14 10:45:05,123 [main] INFO restassuredapi.api.oauthentication.OAuthenticationAPI - {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQxNzI2IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzQ0LjUyNS43NTIxIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI2MTQyODEzNTQ2ODg2IiwiZXhwIjozMDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQyNCwianRpIjoiMWM5OTM3ZTEtYjgwNC00MGRlLWIxNTQtYjE0YTc4ZGJlOWNjIn0.tBEAJyhfmE7hRedQPfb9ANPupucEWYAKsvoXX4RWl9s","refreshToken":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpbklkIjoiQVVUXzQxNzI2IiwicmVxR2F0ZXdheUxvZ2luSWQiOiJwcmV0dXBzIiwidG9rZW5JZCI6IjIwMjIwMjE0MTA0MzQ0LjUyNS43NTIxIiwicmVxR2F0ZXdheVR5cGUiOiJSRVNUIiwiaXNzIjoicHJldHVwcy5vYXV0aCIsInNlcnZpY2VQb3J0IjoiMTkwIiwibXNpc2RuIjoiNzI2MTQyODEzNTQ2ODg2IiwiZXhwIjo2MDAwMDAsInJlcUdhdGV3YXlDb2RlIjoiUkVTVCIsImlhdCI6MTY0NDgzNTQyNCwianRpIjoiOWVhMzA0OWUtNmMxYy00ODBhLWE3NmItN2VmYzQ2MzlkZDVhIn0.GcN4ja2cgjuIi411oEi_uI08q8NXb9loKcmgfCuyvP4","status":200,"messageCode":"9020","message":"Success","errorMap":null}
2022-02-14 10:45:05,127 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>200<br><b>Found: </b>200</pre>
2022-02-14 10:45:05,745 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for Test_OAuthenticationTest -----------------
2022-02-14 10:45:05,746 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/o2c/getUserInfo
2022-02-14 10:45:05,747 [main] INFO restassuredapi.api.BaseAPI - Query Params :

2022-02-14 10:45:05,749 [main] INFO restassuredapi.api.BaseAPI - networkCode : NG

2022-02-14 10:45:05,751 [main] INFO restassuredapi.api.BaseAPI - userId : im8d5NDb

2022-02-14 10:45:05,967 [main] INFO restassuredapi.api.getuserinfoapi.GetUserInfoAPI - {"service":null,"referenceId":null,"status":"400","messageCode":"message.channeltransfer.userdetailnotfound.msg","message":"Details of user im8d5NDb not found.","errorMap":null,"successList":[],"senderUserName":null,"receiverUserName":null,"senderMsisdn":null,"receiverMsisdn":null,"senderCategoryID":null,"receiverCategoryID":null,"senderCategoryName":null,"receiverCategoryName":null,"senderCommissionProfileID":null,"receiverCommissionProfileID":null,"senderCommissionProfileName":null,"receiverCommissionProfileName":null,"senderCommissionProfileSetVersion":null,"receiverCommissionProfileSetVersion":null,"senderUserGradeCode":null,"receiverUserGradeCode":null,"senderUserGradeName":null,"receiverUserGradeName":null,"senderTransferProfileID":null,"receiverTransferProfileID":null,"senderTransferProfileName":null,"receiverTransferProfileName":null,"geographyCode":null,"geographyName":null,"domainCode":null,"domainName":null,"senderDualCommission":null,"receiverDualCommission":null,"userProductDetails":null,"userBalanceDetails":null}
2022-02-14 10:45:05,974 [main] INFO com.utils.Assertion - <pre><b>Expected: </b>Details of user im8d5NDb not found.<br><b>Found: </b>Details of user im8d5NDb not found.</pre>
2022-02-14 10:45:06,533 [main] INFO restassuredapi.test.GetUserInfoApiTest -  -----------------  Test Case Execution completed for A_03_Test_InvalidUserId -----------------
