2022-03-14 10:22:48,970 [main] INFO com.classes.BaseTest - Loading all methods from -masterVO class
2022-03-14 10:22:48,973 [main] INFO com.utils._masterVO - Loading Properties file from: .//src//test//resources//sysconfig//Constant.properties
2022-03-14 10:22:48,976 [main] INFO com.utils._masterVO - Properties File Loaded successfully
2022-03-14 10:22:48,977 [main] INFO com.utils._masterVO - Loading Master Sheet from: src//test//resources//config//DataProvider.xlsx
2022-03-14 10:22:49,538 [main] INFO com.utils._masterVO - Master Sheet Loaded successfully
2022-03-14 10:22:49,540 [main] INFO com.utils._masterVO - Loading Client Library for Client Versioning from: .//src//test//resources//sysconfig//ClientLib.properties
2022-03-14 10:22:49,543 [main] INFO com.utils._masterVO - Client Library Loaded successfully
2022-03-14 10:22:49,786 [main] INFO com.utils._masterVO - loadGeoDomains Map returns ::ZO - AUTbKlI - AUToKa1C
2022-03-14 10:22:49,904 [main] INFO com.utils._masterVO - loadGeoDomains Map returns ::AR - AUT7dba - AUT63dCN
2022-03-14 10:22:50,014 [main] INFO com.utils._masterVO - loadGeoDomains Map returns ::SA - AUTO2Fm - AUTNelnh
2022-03-14 10:22:50,413 [main] INFO com.utils._masterVO - Loading test case file file from: .//src//test//resources//sysconfig//testCaseFile.properties
2022-03-14 10:22:50,430 [main] INFO com.utils._masterVO - Test cases file Loaded successfully
2022-03-14 10:22:50,432 [main] INFO com.utils._masterVO - Loading Web Cases Master file from: .//src//test//resources//config//testCaseFile.properties
2022-03-14 10:22:50,445 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-03-14 10:22:50,475 [main] INFO com.dbrepository.DBHandler - Entered Access Handler :: PostGreSQL
2022-03-14 10:22:50,479 [main] INFO com.commons.CacheController - New Cache DAO Loaded :: UPDATECACHE_VER = 1
2022-03-14 10:22:50,504 [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using log4j logging.
2022-03-14 10:22:50,575 [main] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2022-03-14 10:22:50,649 [main] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 5, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hge9gean11e74z0r93y0m|37911f88, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.postgresql.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hge9gean11e74z0r93y0m|37911f88, idleConnectionTestPeriod -> 0, initialPoolSize -> 10, jdbcUrl -> jdbc:postgresql://172.30.38.120:5432/pretups_trunk, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 20, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 10, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
2022-03-14 10:22:51,805 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getNetworkName()
2022-03-14 10:22:51,938 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: Network Name (Network GGN)
2022-03-14 10:22:51,939 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(AMOUNT_MULT_FACTOR)
2022-03-14 10:22:51,940 [main] INFO com.dbrepository.DBConnectionPool - Active Size:1 Cache Size:2
2022-03-14 10:22:52,059 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (100)
2022-03-14 10:22:52,063 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(MSISDN_PREFIX_LENGTH)
2022-03-14 10:22:52,065 [main] INFO com.dbrepository.DBConnectionPool - Active Size:2 Cache Size:1
2022-03-14 10:22:52,201 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (2)
2022-03-14 10:22:52,203 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(MAX_MSISDN_LENGTH)
2022-03-14 10:22:52,205 [main] INFO com.dbrepository.DBConnectionPool - Active Size:3 Cache Size:0
2022-03-14 10:22:52,646 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (15)
2022-03-14 10:22:52,648 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(USER_PRODUCT_MULTIPLE_WALLET)
2022-03-14 10:22:52,649 [main] INFO com.dbrepository.DBConnectionPool - Active Size:4 Cache Size:2
2022-03-14 10:22:52,803 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (false)
2022-03-14 10:22:52,806 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(EXTERNAL_DATE_FORMAT)
2022-03-14 10:22:52,807 [main] INFO com.dbrepository.DBConnectionPool - Active Size:5 Cache Size:1
2022-03-14 10:22:52,936 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (yyyy/MM/dd)
2022-03-14 10:22:52,938 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DATE_FORMAT_CAL_JAVA)
2022-03-14 10:22:52,941 [main] INFO com.dbrepository.DBConnectionPool - Active Size:6 Cache Size:0
2022-03-14 10:22:53,278 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (yyyy/MM/dd)
2022-03-14 10:22:53,280 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(OTH_COM_CHNL)
2022-03-14 10:22:53,283 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:9
2022-03-14 10:22:53,401 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (false)
2022-03-14 10:22:53,403 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DW_ALLOWED_GATEWAYS)
2022-03-14 10:22:53,406 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:9
2022-03-14 10:22:53,635 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (null)
2022-03-14 10:22:53,636 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DEFAULT_LANGUAGE)
2022-03-14 10:22:53,637 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:9
2022-03-14 10:22:53,886 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (en)
2022-03-14 10:22:53,888 [main] INFO com.dbrepository.PostGreSQLRepository - Entered :: getSystemPreference(DEFAULT_COUNTRY)
2022-03-14 10:22:53,889 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:9
2022-03-14 10:22:54,006 [main] INFO com.dbrepository.PostGreSQLRepository - Query Repository Returns: DEFAULT_VALUE (US)
2022-03-14 10:22:54,008 [main] INFO com.utils._masterVO - Display Locale set to: en_US
2022-03-14 10:23:15,091 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-03-14 10:23:15,122 [main] INFO com.utils._masterVO - Loading Messages Resource properties File from: .//src//test//resources//sysconfig//English.properties
2022-03-14 10:23:15,158 [main] INFO com.utils._masterVO - Messages Resource Properties file Loaded successfully
2022-03-14 10:23:15,159 [main] INFO com.utils._masterVO - Loading Messages Resource properties File from: .//src//test//resources//sysconfig//C2S_English.properties
2022-03-14 10:23:15,168 [main] INFO com.utils._masterVO - Messages Resource Properties file Loaded successfully
2022-03-14 10:23:15,169 [main] INFO com.dbrepository.PostGreSQLRepository - Entered getGatewayDetails('EXTGW','USSD','SMSC')
2022-03-14 10:23:15,171 [main] INFO com.dbrepository.DBConnectionPool - Active Size:0 Cache Size:10
2022-03-14 10:23:15,177 [main] INFO com.dbrepository.PostGreSQLRepository - getGatewayDetails() :: select query: SELECT rmg.gateway_code, mg.gateway_type, rmg.login_id, rmg.PASSWORD, rmg.content_type, rmg.service_port, mg.req_password_plain FROM message_gateway mg, req_message_gateway rmg WHERE mg.gateway_code = rmg.gateway_code AND rmg.gateway_code IN ('EXTGW','USSD','SMSC')
2022-03-14 10:23:15,461 [main] INFO com.dbrepository.PostGreSQLRepository - Database Returns: [[Ljava.lang.Object;@1869fbd2[{{EXTGW,EXTGW,pretups,0971500a350af5c3d1c0b12221a0558c,XML,190,Y},{USSD,USSD,pretups,0971500a350af5c3d1c0b12221a0558c,XML,190,Y},{SMSC,SMSC,pretups,0971500a350af5c3d1c0b12221a0558c,PLAIN,190,Y}}]
2022-03-14 10:23:15,463 [main] INFO com.dbrepository.PostGreSQLRepository - Exiting getGatewayDetails()
2022-03-14 10:23:15,466 [main] INFO com.utils._APIUtil - Entered getAPIServices(EXTGW)
2022-03-14 10:23:15,473 [main] INFO com.utils._APIUtil - Exiting getAPIServices([])
2022-03-14 10:23:15,474 [main] INFO com.utils._masterVO - Loading Gateway Cases Master file from: .//src//test//resources//config//GatewayMaster.xlsx
2022-03-14 10:23:15,579 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,582 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,585 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,595 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,622 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,642 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,644 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,653 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,654 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,654 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,654 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,656 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,657 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,658 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,658 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,675 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,675 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,680 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,681 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,682 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,682 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,683 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,683 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,684 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,684 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,684 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,685 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,685 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,685 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,686 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,686 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,687 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,687 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,687 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,688 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,689 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,689 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,689 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,689 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,690 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,690 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,691 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,691 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:15,691 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException
	at com.utils.ExcelUtility.getCellData(ExcelUtility.java:311)
	at com.utils._masterVO.loadGatewayCases(_masterVO.java:115)
	at com.utils._masterVO.loadExternalServices(_masterVO.java:448)
	at com.utils._masterVO.loadVO(_masterVO.java:81)
	at com.classes.BaseTest.setupReporter(BaseTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

2022-03-14 10:23:16,019 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-03-14 10:23:16,020 [main] INFO com.utils._APIUtil - Entered getAPIServices(USSD)
2022-03-14 10:23:16,022 [main] INFO com.utils._APIUtil - Exiting getAPIServices([])
2022-03-14 10:23:16,024 [main] INFO com.utils._masterVO - Loading Gateway Cases Master file from: .//src//test//resources//config//GatewayMaster.xlsx
2022-03-14 10:23:16,229 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-03-14 10:23:16,231 [main] INFO com.utils._masterVO - Loading Gateway Cases Master file from: .//src//test//resources//config//GatewayMaster.xlsx
2022-03-14 10:23:16,374 [main] INFO com.utils._masterVO - Gateway Cases Master File Loaded successfully
2022-03-14 10:23:37,410 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
2022-03-14 10:23:37,440 [main] INFO com.classes.BaseTest - Completed loading all methods from -masterVO class
2022-03-14 10:25:04,869 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,869 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,870 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,870 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,870 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,870 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,871 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,871 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,871 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,872 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:25:04,890 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:25:04,891 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:25:04,914 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:25:04,914 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:25:05,557 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:23,361 [main] INFO com.classes.BaseTest - java.net.SocketException: Software caused connection abort: recv failed
2022-03-14 10:26:23,368 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:24,268 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:24,268 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:24,271 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:24,271 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:24,280 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:24,299 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:24,302 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:24,768 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:24,770 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:24,772 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:24,772 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:24,776 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:24,792 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:24,795 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:25,219 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:25,219 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:25,220 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:25,220 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:25,223 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:25,235 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:25,238 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:25,753 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:25,753 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:25,753 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:25,753 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:25,757 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:25,770 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:25,773 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:26,392 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:26,392 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:26,393 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:26,393 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:26,398 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:26,410 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:26,413 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:27,003 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:27,003 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:27,005 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:27,005 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:27,008 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:27,020 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:27,023 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:27,680 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:27,680 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:27,682 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:27,682 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:27,685 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:27,703 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:27,707 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:28,280 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:28,280 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:28,281 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:28,281 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:28,285 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:28,296 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:28,299 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:28,888 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:28,889 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:28,891 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:28,891 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:28,896 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:28,906 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:28,909 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:29,569 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:29,569 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:29,571 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:29,571 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:29,576 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:29,589 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:29,591 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:30,175 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:30,175 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:30,178 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:30,178 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:30,182 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:30,195 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:30,199 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:30,917 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:30,917 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:30,919 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:30,919 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:30,923 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:30,938 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:30,940 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:31,491 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:31,491 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:31,493 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:31,493 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:31,496 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:31,509 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:31,512 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:31,934 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:31,934 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:31,936 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:31,936 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:31,939 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:31,951 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:31,954 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:32,548 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:32,548 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:32,550 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:32,550 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:32,557 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:32,577 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:32,581 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:33,278 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_01_Test_success -------------------
2022-03-14 10:26:33,278 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_01_Test_success()
2022-03-14 10:26:33,280 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:33,281 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:33,285 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:33,298 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:33,300 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:34,078 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,079 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,079 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,080 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,080 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,080 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,081 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,081 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,081 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,082 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:34,085 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:34,085 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:34,087 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:34,087 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:34,091 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:34,101 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:34,104 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:34,701 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:34,701 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:34,702 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:34,702 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:34,707 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:34,717 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:34,720 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:35,284 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:35,284 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:35,286 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:35,286 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:35,290 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:35,300 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:35,303 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:35,871 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:35,872 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:35,873 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:35,873 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:35,876 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:35,887 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:35,890 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:36,517 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:36,517 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:36,520 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:36,520 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:36,526 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:36,541 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:36,544 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:37,105 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:37,105 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:37,106 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:37,106 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:37,110 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:37,118 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:37,123 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:37,745 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:37,745 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:37,746 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:37,747 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:37,750 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:37,765 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:37,768 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:38,311 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:38,311 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:38,314 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:38,314 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:38,317 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:38,325 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:38,328 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:39,003 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:39,003 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:39,005 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:39,005 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:39,008 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:39,025 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:39,030 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:39,561 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:39,562 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:39,563 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:39,564 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:39,567 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:39,578 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:39,581 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:40,126 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:40,126 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:40,129 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:40,129 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:40,135 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:40,149 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:40,154 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:40,832 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:40,832 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:40,836 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:40,836 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:40,841 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:40,853 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:40,857 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:41,454 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:41,454 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:41,455 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:41,456 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:41,459 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:41,474 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:41,477 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:42,079 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:42,079 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:42,081 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:42,081 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:42,084 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:42,094 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:42,097 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:42,672 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:42,672 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:42,674 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:42,674 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:42,677 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:42,687 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:42,689 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:43,288 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:43,288 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:43,289 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:43,289 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:43,292 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:43,300 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:43,302 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:43,869 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_09_Test_InvalidMinMsisdnLength -------------------
2022-03-14 10:26:43,869 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_09_Test_InvalidMinMsisdnLength()
2022-03-14 10:26:43,871 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:43,871 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:43,876 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:43,887 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:43,889 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:44,580 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,581 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,582 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,582 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,582 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,583 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,583 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,583 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,584 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,584 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:44,587 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:44,587 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:44,590 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:44,590 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:44,593 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:44,602 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:44,605 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:45,120 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:45,120 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:45,122 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:45,122 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:45,125 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:45,134 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:45,137 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:45,845 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:45,845 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:45,847 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:45,847 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:45,850 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:45,860 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:45,863 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:46,526 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:46,526 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:46,529 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:46,529 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:46,535 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:46,548 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:46,552 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:47,234 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:47,234 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:47,238 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:47,238 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:47,241 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:47,255 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:47,258 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:47,934 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:47,934 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:47,935 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:47,935 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:47,938 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:47,950 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:47,952 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:48,611 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:48,611 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:48,614 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:48,614 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:48,617 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:48,627 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:48,633 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:49,279 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:49,279 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:49,280 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:49,280 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:49,283 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:49,292 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:49,295 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:49,920 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:49,920 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:49,923 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:49,923 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:49,928 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:49,937 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:49,940 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:50,643 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:50,643 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:50,646 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:50,646 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:50,650 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:50,658 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:50,661 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:51,253 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:51,254 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:51,255 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:51,255 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:51,258 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:51,266 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:51,268 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:51,831 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:51,831 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:51,832 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:51,832 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:51,835 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:51,842 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:51,846 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:52,448 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:52,448 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:52,451 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:52,451 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:52,456 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:52,463 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:52,467 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:53,089 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:53,089 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:53,091 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:53,091 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:53,094 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:53,102 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:53,105 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:53,733 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:53,734 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:53,735 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:53,735 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:53,739 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:53,749 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:53,752 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:54,439 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:54,439 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:54,440 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:54,441 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:54,445 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:54,455 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:54,461 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:54,996 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_10_Test_InvalidMinLoginIdLength -------------------
2022-03-14 10:26:54,996 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_10_Test_InvalidMinLoginIdLength()
2022-03-14 10:26:54,997 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:54,998 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:55,001 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:55,009 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:55,012 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:55,632 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,632 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,633 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,634 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,634 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,634 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,634 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,635 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,635 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,635 [main] INFO com.utils.ExcelUtility - java.lang.NullPointerException

2022-03-14 10:26:55,642 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:55,642 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:55,644 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:55,644 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:55,648 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:55,657 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:55,660 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:56,234 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:56,235 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:56,237 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:56,238 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:56,242 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:56,255 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:56,259 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:56,760 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:56,760 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:56,761 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:56,761 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:56,765 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:56,775 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:56,779 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:57,300 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:57,300 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:57,301 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:57,301 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:57,304 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:57,311 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:57,314 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:57,965 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:57,965 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:57,967 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:57,967 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:57,969 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:57,977 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:57,979 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:58,493 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:58,493 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:58,494 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:58,494 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:58,498 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:58,507 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:58,511 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:59,167 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:59,168 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:59,170 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:59,171 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:59,175 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:59,190 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:59,192 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:59,745 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:26:59,745 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:26:59,746 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:26:59,746 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:26:59,750 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:26:59,757 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:26:59,760 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:00,339 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:00,339 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:00,340 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:00,340 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:00,343 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:00,351 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:00,355 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:00,993 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:00,993 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:00,994 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:00,994 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:00,998 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:01,006 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:01,010 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:01,542 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:01,542 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:01,543 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:01,544 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:01,547 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:01,555 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:01,557 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:02,185 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:02,185 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:02,188 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:02,188 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:02,192 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:02,204 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:02,207 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:02,882 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:02,882 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:02,885 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:02,885 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:02,891 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:02,901 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:02,904 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:03,415 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:03,415 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:03,416 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:03,416 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:03,421 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:03,428 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:03,430 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:03,860 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:03,861 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:03,862 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:03,862 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:03,866 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:03,874 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:03,877 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:04,471 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:04,471 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:04,472 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:04,472 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:04,476 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:04,488 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:04,491 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:05,022 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For A_13_Test_InvalidDomainCodeData -------------------
2022-03-14 10:27:05,022 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered A_13_Test_InvalidDomainCodeData()
2022-03-14 10:27:05,024 [main] INFO restassuredapi.test.AutoCompleteUserDetails - ------------------ Test Case Execution Started For Test_OAuthenticationTest -------------------
2022-03-14 10:27:05,024 [main] INFO restassuredapi.test.AutoCompleteUserDetails - Entered Test_OAuthenticationTest()
2022-03-14 10:27:05,031 [main] INFO restassuredapi.api.BaseAPI - API URL: http://172.30.38.232:6789/pretups/rstapi/v1/generateTokenAPI
2022-03-14 10:27:05,039 [main] INFO com.classes.BaseTest - java.net.NoRouteToHostException: No route to host: connect
2022-03-14 10:27:05,042 [main] ERROR com.sshmanager.SSHService - Error while getting SSH Server Instance : com.jcraft.jsch.JSchException: java.net.NoRouteToHostException: No route to host: connect
