<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MCKL-20005142" name="restassuredapi.test.O2CApprovalList" tests="11" failures="0" timestamp="14 Feb 2022 15:03:46 GMT" time="152.427" errors="1">
  <testcase name="A_04_Test_Invalid_domain" time="1.337" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_03_Test_Invalid_level" time="1.316" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_03_Test_Invalid_level" time="1.382" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_02_Test_Success_Msisdn" time="1.354" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_05_Test_Invalid_msisdn" time="1.330" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_05_Test_Invalid_msisdn" time="1.316" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_01_TEST_SUCCESS" time="12.001" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="tearDown" time="107.234" classname="restassuredapi.test.O2CApprovalList">
    <error type="java.io.FileNotFoundException" message="C:\Users\chetan.chawla\Desktop\BuildID.txt (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\chetan.chawla\Desktop\BuildID.txt (The system cannot find the path specified)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at com.webaut.ctreportutil.util.BuildIDUtil.getBuildID(BuildIDUtil.java:61)
at com.webaut.ctreportutil.CTReporter.BuildIDConfigurator(CTReporter.java:20)
at com.classes.BaseTest.tearDown(BaseTest.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- tearDown -->
  <testcase name="A_01_TEST_SUCCESS" time="13.479" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_04_Test_Invalid_domain" time="1.607" classname="restassuredapi.test.O2CApprovalList"/>
  <testcase name="A_02_Test_Success_Msisdn" time="10.071" classname="restassuredapi.test.O2CApprovalList"/>
</testsuite> <!-- restassuredapi.test.O2CApprovalList -->
